/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package validadorbean;

/**
 *
 * @author aluno
 */
public class CampoTextoBean extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer CampoTextoBean
     */
    public CampoTextoBean() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    private String conteudo = "";

    /**
     * Get the value of conteudo
     *
     * @return the value of conteudo
     */
    public String getConteudo() {
        return conteudo;
    }

    /**
     * Set the value of conteudo
     *
     * @param conteudo new value of conteudo
     */
    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }

    private Boolean valido = false;

    /**
     * Get the value of valido
     *
     * @return the value of valido
     */
    public Boolean getValido() {
        return valido;
    }

    private Validador validador;

    /**
     * Get the value of validador
     *
     * @return the value of validador
     */
    public Validador getValidador() {
        return validador;
    }

    /**
     * Set the value of validador
     *
     * @param validador new value of validador
     */
    public void setValidador(Validador validador) {
        this.validador = validador;
    }

    private String corEstado = "vermelho";

    /**
     * Get the value of corEstado
     *
     * @return the value of corEstado
     */
    public String getCorEstado() {
        return corEstado;
    }

    /**
     * Set the value of corEstado
     *
     * @param corEstado new value of corEstado
     */
    public void setCorEstado(String corEstado) {
        this.corEstado = corEstado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoTexto = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        CampoTexto.setText("Campo de texto");
        CampoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoActionPerformed(evt);
            }
        });
        add(CampoTexto);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTextoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoTexto;
    // End of variables declaration//GEN-END:variables
}
